version: "3.8"
services:
    database:
        container_name: mysql
        build: ./database
        image: mysql:latest
        environment:
            MYSQL_ROOT_PASSWORD: password
    backend:
        container_name: backend
        build: ./backend
        image: backend
        environment:
            DATABASE_URI: mysql+pymysql://root:password@mysql:3306/users
        depends_on:
            - database
        ports:
        - target: 5001
          published: 5001
          protocol: tcp
    frontend:
        container_name: frontend
        build: ./frontend
        image: frontend
        ports:
        - target: 5000
          published: 5000
          protocol: tcp

